In [21]:
import mysql.connector

In [22]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="1997",
  auth_plugin='mysql_native_password',
  database='youtubedata'
)

mycursor = mydb.cursor()

NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported

In [9]:
mycursor.execute("use youtubedata")

NameError: name 'cursorclass' is not defined

In [4]:
 mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('comment_detail',)
('video_detail',)
('youtubedata',)

In [2]:
def channel_data(channel_id):
    channel_ids=[]
    request = youtube.channels().list(
    part="snippet,contentDetails,statistics",      
    id=channel_id
    )
    response = request.execute()
    
    data={
        "channel_name":response['items'][0]['snippet']['title'],
        "channel_id":channel_id,
        "publishedAT":response['items'][0]['snippet']['publishedAt'],
        "video_count":response['items'][0]['statistics']['videoCount'],
        "subscription_count":response['items'][0]['statistics']['subscriberCount'],
        "channel_views":response['items'][0]['statistics']['viewCount'],
        "channel_description":response['items'][0]['snippet']['description'],
        "playlist_id":response['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    }
    channel_ids.append(data) 
    return channel_ids

In [3]:
ch_ids=channel_data('UCJcCB-QYPIBcbKcBQOTwhiA')

In [4]:
ch_ids

[{'channel_name': 'Vj Siddhu Vlogs',
  'channel_id': 'UCJcCB-QYPIBcbKcBQOTwhiA',
  'publishedAT': '2023-06-14T07:41:42.139364Z',
  'video_count': '201',
  'subscription_count': '2720000',
  'channel_views': '448324521',
  'channel_description': 'Hello guys! Welcome to my channel! !\n\nMy channel will take you into the details of my life and give a glimpse of what inspires me to do what I do. \n\nGet ready to watch my latest vlogs depicting life in detail that will make you slow down and enjoy life a little better. Subscribe to my channel and stay connected!  \n\nFor Business inquiries please contact us :7200571056\nGmail : vjsidduvlogsadv@gmail.com \n______________________________\n\nDigital Partner - Divo\nDivo is one of the leading digital media companies in South India working with brands and content creators across genres.\n',
  'playlist_id': 'UUJcCB-QYPIBcbKcBQOTwhiA'}]

In [8]:
channel_id = []

# Process each dictionary in the list
for ch_id in ch_ids:
    # Create a tuple from dictionary values and append to video_data
    data = tuple(ch_id.values())
    channel_id.append(data)

In [9]:
channel_ids=channel_id

In [10]:
channel_ids

[('Vj Siddhu Vlogs',
  'UCJcCB-QYPIBcbKcBQOTwhiA',
  '2023-06-14T07:41:42.139364Z',
  '201',
  '2720000',
  '448324521',
  'Hello guys! Welcome to my channel! !\n\nMy channel will take you into the details of my life and give a glimpse of what inspires me to do what I do. \n\nGet ready to watch my latest vlogs depicting life in detail that will make you slow down and enjoy life a little better. Subscribe to my channel and stay connected!  \n\nFor Business inquiries please contact us :7200571056\nGmail : vjsidduvlogsadv@gmail.com \n______________________________\n\nDigital Partner - Divo\nDivo is one of the leading digital media companies in South India working with brands and content creators across genres.\n',
  'UUJcCB-QYPIBcbKcBQOTwhiA')]

In [5]:
mycursor.execute("""
    CREATE TABLE Youtubedata (
        channel_name VARCHAR(100),
        channel_id VARCHAR(80) PRIMARY KEY,
        subscriber INT,
        views INT,
        Total_videos INT,
        channel_description TEXT,
        playlist_id VARCHAR(80)
    )
""")
mydb.commit()

ProgrammingError: 1050 (42S01): Table 'youtubedata' already exists

In [ ]:
def tables():
    Youtube_data()

In [ ]:
mycursor = mydb.cursor()

# Define the SQL INSERT statement
sql = """
    INSERT INTO Youtubedata (channel_name, channel_id, subscriber, views, Total_videos, channel_description, playlist_id)
    VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

# Define the values to be inserted
values = [
  
    (
        "Skills Maker TV",
        "UCgqFE36SRlascaK19bmYt8A",
        1190000,
        120228016,
        675,
        "Hello friends, Welcome to 'SkillsMakers tv', I created this channel on 16 May 2013, my motive behind creating this channel was to make Easy to Understand, Tech Videos in Tamil, and I wanted each and every Individual whoever is interested in technology to be able to understand it in the easiest possible way. I am a computer technician living in India, doing this as my Hobby, I post a new video weekly, on topics that create the most confusion. Please SUBSCRIBE to SkillsMakers tv. Thanks.\n\nVideo Topics:\n1)Mobile SETTINGS Tips Tricks in Tamil\n2)Mobile apps & computer software review in Tamil\n3)Internet Settings in Tamil\n4)How To Tutorials in Tamil\n5)Tech Explain in Tamil\n6)Computer in Tamil\n7)Gadgets Reviews unboxing & Comparison in Tamil\n\nI also have one more channel (Skills Maker TV Shorts) which is all about our life channel. Please don’t forget to subscribe to this also.\n\nFor Business enquiries: skillmaker05@gmail.com\n\nI do not provide tech support over e-mail.",
        "UUgqFE36SRlascaK19bmYt8A"
    )
]

# Execute the SQL statement with the values
mycursor.executemany(sql, values)

# Commit the transaction
mydb.commit()

# Close the cursor and connection
mycursor.close()
mydb.close()

print(mycursor.rowcount, "records inserted.")

1 records inserted.

In [ ]:
# Create a cursor object
mycursor = mydb.cursor()

# Define the SQL INSERT statement
sql = """
    INSERT INTO Youtubedata (channel_name, channel_id, subscriber, views, Total_videos, channel_description, playlist_id)
    VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

# Define the values to be inserted
values =channel_ids

# Execute the SQL statement with the values
mycursor.executemany(sql, values)

# Commit the transaction
mydb.commit()

# Close the cursor and connection
mycursor.close()
mydb.close()

print(mycursor.rowcount, "records inserted.")

In [ ]:
# Create a cursor object
mycursor = mydb.cursor()

# Define the SQL INSERT statement
sql = """
    INSERT INTO Youtubedata (channel_name, channel_id, subscriber, views, Total_videos, channel_description, playlist_id)
    VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

# Define the values to be inserted
values = [
    (
        "Vj Siddhu Vlogs",
        "UCJcCB-QYPIBcbKcBQOTwhiA",
        2710000,
        1441747099,
        199,
        "Hello guys! Welcome to my channel! My channel will take you into the details of my life and give a glimpse of what inspires me to do what I do. Get ready to watch my latest vlogs depicting life in detail that will make you slow down and enjoy life a little better. Subscribe to my channel and stay connected! For Business inquiries please contact us: 7200571056 Gmail: vjsidduvlogsadv@gmail.com Digital Partner - Divo Divo is one of the leading digital media companies in South India working with brands and content creators across genre.",
        "UUJcCB-QYPIBcbKcBQOTwhiA"
    ),
    (
        "Irfan's view",
        "UCnjU1FHmao9YNfPzE039YTw",
        4360000,
        1415118888,
        2499,
        "I love Food and Living. So, I vlog and do Food Reviews.",
        "UCgqFE36SRlascaK19bmYt8A"
    ),
    (
        "Peppa Foodie",
        "UC8wwXAm77RNzVN-cJOy8t8g",
        1770000,
        1264901941,
        1331,
        "Vanakam Makkale ;-) This is your Boy Peppa Here xD 🤟🏻✨ and this is a Public Space to Share all My Food 🍜🥢🍣🍕 & Travel Adventures ✈️🛳 So Sit back and Enjoy the Videos and if you Happen to Like them Do Subscribe xD",
        "UU8wwXAm77RNzVN-cJOy8t8g"
    ),
    (
        "Gpmuthu Official",
        "UCkHngIP8_GpujNDSdUfhETw",
        1620000,
        331446299,
        1029,
        "For Business Enquiries - skanmstudio1984@gmail.com",
        "UUkHngIP8_GpujNDSdUfhETw"
    ),
    (
        "Shabarinath Premlal",
        "UCQqmjKQBKQkRbWbSntYJX0Q",
        210,
        2600,
        10,
        "",
        "UUQqmjKQBKQkRbWbSntYJX0Q"
    ),
    (
        "Ishwarya Mahesh kumar",
        "UCzFN1MbdBvcNNHiJpa3hm2g",
        10700,
        3887348,
        260,
        "",
        "UUzFN1MbdBvcNNHiJpa3hm2g"
    ),
    (
        "kk abirami vlog",
        "UC9zWJT-ftzVNfeng8bZACNw",
        2230,
        392025,
        595,
        "Kk abirami vlog",
        "UU9zWJT-ftzVNfeng8bZACNw"
    ),
    (
        "Abarnasivabalan vlogs",
        "UC-XZPyAjTd9oLGF7brGrD2g",
        417000,
        212291299,
        469,
        "My daily vlogs",
        "UU-XZPyAjTd9oLGF7brGrD2g"
    )
]

# Execute the SQL statement with the values
mycursor.executemany(sql, values)

# Commit the transaction
mydb.commit()

# Close the cursor and connection
mycursor.close()
mydb.close()

print(mycursor.rowcount, "records inserted.")

8 records inserted.

In [1]:
import googleapiclient.discovery
api_service_name = "youtube"
api_version = "v3"
api_key="AIzaSyBMXvNN-k7uLBWlbaFYF5b1iMpp_ZO1ehc"
youtube = googleapiclient.discovery.build(
        api_service_name, api_version,developerKey=api_key)

In [ ]:
def get_video_id(channel_id):
    request = youtube.channels().list(
    part="contentDetails",
    id=channel_id
    )
    response=request.execute() 
    playlist_Id=response['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    response1=youtube.playlistItems().list(part='snippet',
                                           playlistId=playlist_Id,maxResults=50).execute()
    video_id=[]
    for i in range(len(response1['items'])):
        video_id.append(response1['items'][i]['snippet']['resourceId']['videoId'])
    return video_id

In [ ]:
video_id=get_video_id("UC8wwXAm77RNzVN-cJOy8t8g")

In [ ]:
def get_video_detail(video_id):
    detail=[]
    for video_ids in video_id: 
        request = youtube.videos().list(
            part="snippet,contentDetails,statistics",
            id=video_id
        )
        response2 = request.execute()
    
        for item in response2['items']:  
                data = {
                    "channel_name": item['snippet']['channelTitle'],
                    "video_id": item['id'],
                    "title": item['snippet']['title'],  
                    "View_count": item['statistics'].get('viewCount', '0'),
                    "like_count": item['statistics'].get('likeCount', '0'),
                    "comments_count": item['statistics'].get('commentCount', '0'),
                }
                detail.append(data)
        return detail

In [ ]:
videos=get_video_detail(video_id)

In [ ]:
videos

[{'channel_name': 'Peppa Foodie',
  'video_id': '2u8qlSBykYY',
  'title': 'SECRET 🤫 Sweet of Chennai 🤯‼️| #shorts',
  'View_count': '91450',
  'like_count': '12833',
  'comments_count': '13'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '2r9UJa_EAHA',
  'title': 'Trivandrum Chicken Fry ✨🔥⁉️| #shorts',
  'View_count': '69169',
  'like_count': '10901',
  'comments_count': '17'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'wqCa4BkEgbo',
  'title': '₹100 Ku SRM Students Atti Spot 🔥🙌🏻 | #shorts',
  'View_count': '104318',
  'like_count': '11920',
  'comments_count': '17'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'J6qsAGQaSsM',
  'title': 'Budget-ல துணி Vangnuma ⁉️👔✨| #shorts',
  'View_count': '38130',
  'like_count': '3645',
  'comments_count': '11'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'EkNDYiAFXrc',
  'title': 'Katchi Sera ❌ Aasa Kooda ✅ | #shorts',
  'View_count': '34561',
  'like_count': '3770',
  'comments_count': '7'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '0OCKR1nZSRY',
  'title': 'SECRET 🤫 Gravy of Chennai 🔥 | #shorts',
  'View_count': '168267',
  'like_count': '19802',
  'comments_count': '66'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'pYskowMXyRc',
  'title': 'The Best Tiramisu in Chennai ✨🛐🔥 | GOAT -  Episode 2',
  'View_count': '11104',
  'like_count': '455',
  'comments_count': '12'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'A_7mX0BO7M8',
  'title': 'Sundal மாமா Oru Vibe ✨😍🔥| #shorts',
  'View_count': '1094442',
  'like_count': '121009',
  'comments_count': '163'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'cHfaLRDZycQ',
  'title': 'OG 🛐 Andhra Mess in Town 🔥✨😍 | The National Lodge',
  'View_count': '15059',
  'like_count': '687',
  'comments_count': '16'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'S87fXrOXLeM',
  'title': 'Mango 🥭 Crushed Ice ❄️🧊| #shorts',
  'View_count': '131357',
  'like_count': '10554',
  'comments_count': '16'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'r7pwft0mkJ0',
  'title': 'Ellame Pochu 😭 - No Audio ☠️❌ | #shorts',
  'View_count': '77789',
  'like_count': '8158',
  'comments_count': '12'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'CeENNaCscsY',
  'title': 'Do Not Visit ❌ This Spot 😭| #shorts',
  'View_count': '1228988',
  'like_count': '91142',
  'comments_count': '165'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'aYT1_imqxV0',
  'title': 'Iniki LIPS 💋 Try Panlama 🌚 | #shorts',
  'View_count': '101896',
  'like_count': '8786',
  'comments_count': '22'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'qtEyFm5RoP4',
  'title': 'BUDGET-ல Furniture 🪵 Ah 😮| #shorts',
  'View_count': '596334',
  'like_count': '24762',
  'comments_count': '134'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'AcLmGdGgghw',
  'title': 'TOP 5 🏆 Hot Chocolate 😍☕️ | #shorts',
  'View_count': '77943',
  'like_count': '9589',
  'comments_count': '24'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'SFJ7BPG16qA',
  'title': 'OFFER ‼️😍 for School Bags 👦🏻😍 | #shorts',
  'View_count': '78700',
  'like_count': '5370',
  'comments_count': '18'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'r8iAWtfmfa4',
  'title': 'Eating at Biggies Burgers for 24 Hours 🤯⏳🍔 | Peppa Foodie',
  'View_count': '23299',
  'like_count': '847',
  'comments_count': '22'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '15INND4HNeg',
  'title': 'Budget-ல PRIVATE Villa 🏘️😍🍻| #shorts',
  'View_count': '303612',
  'like_count': '26447',
  'comments_count': '32'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '-PoneupMoAg',
  'title': 'Biryani Raid 🤯‼️in Mogapppair | #shorts',
  'View_count': '354333',
  'like_count': '40550',
  'comments_count': '39'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'UJUO65TpWl8',
  'title': '**Mmala Idhu Dhan Da RASAM 🤯🔥‼️',
  'View_count': '216592',
  'like_count': '20151',
  'comments_count': '55'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '5PlLBd-y1wE',
  'title': 'Girlfriend Oda 💋♥️ Majja Dhan 🌚 | #shorts',
  'View_count': '748597',
  'like_count': '56040',
  'comments_count': '185'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'nMq5hnRWEaU',
  'title': 'வெள்ளை கரடி Ippadi dhan Irukuma 😂🐼🔥| #shorts',
  'View_count': '184978',
  'like_count': '19973',
  'comments_count': '31'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'omoHdSiaO_s',
  'title': 'பழய சோறு ku ₹110 Rupees ah 🤯‼️| #shorts',
  'View_count': '243365',
  'like_count': '25620',
  'comments_count': '55'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'h65Ps65s2T8',
  'title': 'உண்மை யா Sollunga Bro 🤯‼️| #shorts',
  'View_count': '1826242',
  'like_count': '80317',
  'comments_count': '178'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '-Crtx6hf_GA',
  'title': 'தேங்காய் Mutton Soru 🥥🍖⁉️| #shorts',
  'View_count': '236176',
  'like_count': '22437',
  'comments_count': '38'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'LXM4c0Ig0gw',
  'title': 'Telugu சாப்பாடு Ku Oru OG Spot 🛐🔥✨| #shortsa',
  'View_count': '169351',
  'like_count': '17270',
  'comments_count': '45'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'eoWDrOhAykc',
  'title': 'Chennai La ⁉️ 10 T-Shirts 👕for ₹1000 INR 🤯| Wow Clothing',
  'View_count': '89811',
  'like_count': '2536',
  'comments_count': '84'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'rDSTSYnlXUQ',
  'title': 'Slave ah Mariten 🛐👑✨| #shorts',
  'View_count': '276592',
  'like_count': '32427',
  'comments_count': '31'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '3WLE8oqBbac',
  'title': 'Side Dish Ready 🍻🥩✅ | #shorts',
  'View_count': '407726',
  'like_count': '39762',
  'comments_count': '67'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '1V8HWxo4QdI',
  'title': 'GYM Trainer 🏋🏻️ Caught Me ☠️❌ | #shorts',
  'View_count': '195181',
  'like_count': '24160',
  'comments_count': '19'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'xkLXFPrGAw8',
  'title': 'Banana Leaf ❌ Paper Leaf ✅ | #shorts',
  'View_count': '705238',
  'like_count': '63614',
  'comments_count': '102'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '0viBz5omKmY',
  'title': 'Oru முட்டை🍳₹75 INR Ah ☠️⚰️⁉️ | #shorts',
  'View_count': '1169074',
  'like_count': '124227',
  'comments_count': '382'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '3j3uqDCx4C8',
  'title': '7/11 Food in Malaysia 🇲🇾🍱✨‼️| #shorts',
  'View_count': '308636',
  'like_count': '26287',
  'comments_count': '38'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'WjT_bbaVafE',
  'title': 'தவள கறி 🐸 Virundhu 😭☠️🔥 | #shorts',
  'View_count': '904139',
  'like_count': '47844',
  'comments_count': '195'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'mWXe1z_qsiM',
  'title': 'Malaysian 🔥🤤 Famous Ramly Burger 🇲🇾🍔 | #shorts',
  'View_count': '322062',
  'like_count': '31737',
  'comments_count': '45'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '5c6Ff5-jkrc',
  'title': 'Reality of Anna Nagar ☠️⚰️‼️| #shorts',
  'View_count': '214888',
  'like_count': '25336',
  'comments_count': '97'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'gR_Tr1icOOQ',
  'title': 'FLASH SALE‼️in Chennai 🤯| #shorts',
  'View_count': '67560',
  'like_count': '5977',
  'comments_count': '27'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'Hm9qIuTogzY',
  'title': 'Malaysia-ல அப்படி Enna Panna ⁉️🔥🌚| #shorts',
  'View_count': '148230',
  'like_count': '14076',
  'comments_count': '28'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'oMVl7RVH5pE',
  'title': 'Batu Caves Murugan Temple 🔥😍🇲🇾 | Peppa Foodie',
  'View_count': '12375',
  'like_count': '559',
  'comments_count': '7'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'Fv3_6jXVAE8',
  'title': 'அப்பா Ku Surprise GIFT 🎁🎉 | #shorts',
  'View_count': '500678',
  'like_count': '35888',
  'comments_count': '157'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'pPJp664_HYk',
  'title': 'Legendary Malaysian 🇲🇾 Restaurant in Chennai 🔥✨🎉 | #shortsen',
  'View_count': '221628',
  'like_count': '22593',
  'comments_count': '48'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'iydxzyyHkPI',
  'title': 'TRENDING ⚡️ Spot in Malaysia 🇲🇾🔥| #shorts',
  'View_count': '126884',
  'like_count': '12754',
  'comments_count': '23'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '-MFJHJxAlzE',
  'title': 'LOK LOK In Malaysia 🤢🔥❌ | #shorts',
  'View_count': '1123440',
  'like_count': '79417',
  'comments_count': '124'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'DIksTLGTjnI',
  'title': 'தமிழன் அன்பு in Malaysia 🇲🇾♥️🫂 | #shorts',
  'View_count': '413176',
  'like_count': '39859',
  'comments_count': '38'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'SRcNmJAbWxw',
  'title': 'மரண Mutton Sapadu 🥩😍🔥| #shorts',
  'View_count': '1737912',
  'like_count': '140971',
  'comments_count': '235'},
 {'channel_name': 'Peppa Foodie',
  'video_id': '9YMWKe_IuwA',
  'title': "Let's Try CHINESE 🇨🇳 Breakfast ✨‼️| #shorts",
  'View_count': '1272029',
  'like_count': '82894',
  'comments_count': '145'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'xoirwBxYEps',
  'title': 'Night Life 😍 of Malaysia 🇲🇾🔞 | #shorts',
  'View_count': '1515930',
  'like_count': '122178',
  'comments_count': '155'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'hQvO5nzErLA',
  'title': 'Mango 🥭 Sticky Rice ♥️ நம்ம ஊரு சோறு Ah 🔥‼️| #shorts',
  'View_count': '297998',
  'like_count': '27427',
  'comments_count': '64'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'sdc5ZXQfFu4',
  'title': 'Malaysia-ல இப்படி Oru Food Street ah 🔥🇲🇾‼️| #shorts',
  'View_count': '396254',
  'like_count': '36874',
  'comments_count': '55'},
 {'channel_name': 'Peppa Foodie',
  'video_id': 'Ggz7-8z9zCk',
  'title': 'Roti Canai and Teh Tarik 🔥🇲🇾 in Malaysia | Peppa Foodie',
  'View_count': '33744',
  'like_count': '896',
  'comments_count': '15'}]

In [ ]:
video_data = []

# Process each dictionary in the list
for video in videos:
    # Create a tuple from dictionary values and append to video_data
    data = tuple(video.values())
    video_data.append(data)

In [ ]:
videos=video_data

In [ ]:
videos

[('Peppa Foodie',
  '2u8qlSBykYY',
  'SECRET 🤫 Sweet of Chennai 🤯‼️| #shorts',
  '91450',
  '12833',
  '13'),
 ('Peppa Foodie',
  '2r9UJa_EAHA',
  'Trivandrum Chicken Fry ✨🔥⁉️| #shorts',
  '69169',
  '10901',
  '17'),
 ('Peppa Foodie',
  'wqCa4BkEgbo',
  '₹100 Ku SRM Students Atti Spot 🔥🙌🏻 | #shorts',
  '104318',
  '11920',
  '17'),
 ('Peppa Foodie',
  'J6qsAGQaSsM',
  'Budget-ல துணி Vangnuma ⁉️👔✨| #shorts',
  '38130',
  '3645',
  '11'),
 ('Peppa Foodie',
  'EkNDYiAFXrc',
  'Katchi Sera ❌ Aasa Kooda ✅ | #shorts',
  '34561',
  '3770',
  '7'),
 ('Peppa Foodie',
  '0OCKR1nZSRY',
  'SECRET 🤫 Gravy of Chennai 🔥 | #shorts',
  '168267',
  '19802',
  '66'),
 ('Peppa Foodie',
  'pYskowMXyRc',
  'The Best Tiramisu in Chennai ✨🛐🔥 | GOAT -  Episode 2',
  '11104',
  '455',
  '12'),
 ('Peppa Foodie',
  'A_7mX0BO7M8',
  'Sundal மாமா Oru Vibe ✨😍🔥| #shorts',
  '1094442',
  '121009',
  '163'),
 ('Peppa Foodie',
  'cHfaLRDZycQ',
  'OG 🛐 Andhra Mess in Town 🔥✨😍 | The National Lodge',
  '15059',
  '687',
  '16'),
 ('Peppa Foodie',
  'S87fXrOXLeM',
  'Mango 🥭 Crushed Ice ❄️🧊| #shorts',
  '131357',
  '10554',
  '16'),
 ('Peppa Foodie',
  'r7pwft0mkJ0',
  'Ellame Pochu 😭 - No Audio ☠️❌ | #shorts',
  '77789',
  '8158',
  '12'),
 ('Peppa Foodie',
  'CeENNaCscsY',
  'Do Not Visit ❌ This Spot 😭| #shorts',
  '1228988',
  '91142',
  '165'),
 ('Peppa Foodie',
  'aYT1_imqxV0',
  'Iniki LIPS 💋 Try Panlama 🌚 | #shorts',
  '101896',
  '8786',
  '22'),
 ('Peppa Foodie',
  'qtEyFm5RoP4',
  'BUDGET-ல Furniture 🪵 Ah 😮| #shorts',
  '596334',
  '24762',
  '134'),
 ('Peppa Foodie',
  'AcLmGdGgghw',
  'TOP 5 🏆 Hot Chocolate 😍☕️ | #shorts',
  '77943',
  '9589',
  '24'),
 ('Peppa Foodie',
  'SFJ7BPG16qA',
  'OFFER ‼️😍 for School Bags 👦🏻😍 | #shorts',
  '78700',
  '5370',
  '18'),
 ('Peppa Foodie',
  'r8iAWtfmfa4',
  'Eating at Biggies Burgers for 24 Hours 🤯⏳🍔 | Peppa Foodie',
  '23299',
  '847',
  '22'),
 ('Peppa Foodie',
  '15INND4HNeg',
  'Budget-ல PRIVATE Villa 🏘️😍🍻| #shorts',
  '303612',
  '26447',
  '32'),
 ('Peppa Foodie',
  '-PoneupMoAg',
  'Biryani Raid 🤯‼️in Mogapppair | #shorts',
  '354333',
  '40550',
  '39'),
 ('Peppa Foodie',
  'UJUO65TpWl8',
  '**Mmala Idhu Dhan Da RASAM 🤯🔥‼️',
  '216592',
  '20151',
  '55'),
 ('Peppa Foodie',
  '5PlLBd-y1wE',
  'Girlfriend Oda 💋♥️ Majja Dhan 🌚 | #shorts',
  '748597',
  '56040',
  '185'),
 ('Peppa Foodie',
  'nMq5hnRWEaU',
  'வெள்ளை கரடி Ippadi dhan Irukuma 😂🐼🔥| #shorts',
  '184978',
  '19973',
  '31'),
 ('Peppa Foodie',
  'omoHdSiaO_s',
  'பழய சோறு ku ₹110 Rupees ah 🤯‼️| #shorts',
  '243365',
  '25620',
  '55'),
 ('Peppa Foodie',
  'h65Ps65s2T8',
  'உண்மை யா Sollunga Bro 🤯‼️| #shorts',
  '1826242',
  '80317',
  '178'),
 ('Peppa Foodie',
  '-Crtx6hf_GA',
  'தேங்காய் Mutton Soru 🥥🍖⁉️| #shorts',
  '236176',
  '22437',
  '38'),
 ('Peppa Foodie',
  'LXM4c0Ig0gw',
  'Telugu சாப்பாடு Ku Oru OG Spot 🛐🔥✨| #shortsa',
  '169351',
  '17270',
  '45'),
 ('Peppa Foodie',
  'eoWDrOhAykc',
  'Chennai La ⁉️ 10 T-Shirts 👕for ₹1000 INR 🤯| Wow Clothing',
  '89811',
  '2536',
  '84'),
 ('Peppa Foodie',
  'rDSTSYnlXUQ',
  'Slave ah Mariten 🛐👑✨| #shorts',
  '276592',
  '32427',
  '31'),
 ('Peppa Foodie',
  '3WLE8oqBbac',
  'Side Dish Ready 🍻🥩✅ | #shorts',
  '407726',
  '39762',
  '67'),
 ('Peppa Foodie',
  '1V8HWxo4QdI',
  'GYM Trainer 🏋🏻️ Caught Me ☠️❌ | #shorts',
  '195181',
  '24160',
  '19'),
 ('Peppa Foodie',
  'xkLXFPrGAw8',
  'Banana Leaf ❌ Paper Leaf ✅ | #shorts',
  '705238',
  '63614',
  '102'),
 ('Peppa Foodie',
  '0viBz5omKmY',
  'Oru முட்டை🍳₹75 INR Ah ☠️⚰️⁉️ | #shorts',
  '1169074',
  '124227',
  '382'),
 ('Peppa Foodie',
  '3j3uqDCx4C8',
  '7/11 Food in Malaysia 🇲🇾🍱✨‼️| #shorts',
  '308636',
  '26287',
  '38'),
 ('Peppa Foodie',
  'WjT_bbaVafE',
  'தவள கறி 🐸 Virundhu 😭☠️🔥 | #shorts',
  '904139',
  '47844',
  '195'),
 ('Peppa Foodie',
  'mWXe1z_qsiM',
  'Malaysian 🔥🤤 Famous Ramly Burger 🇲🇾🍔 | #shorts',
  '322062',
  '31737',
  '45'),
 ('Peppa Foodie',
  '5c6Ff5-jkrc',
  'Reality of Anna Nagar ☠️⚰️‼️| #shorts',
  '214888',
  '25336',
  '97'),
 ('Peppa Foodie',
  'gR_Tr1icOOQ',
  'FLASH SALE‼️in Chennai 🤯| #shorts',
  '67560',
  '5977',
  '27'),
 ('Peppa Foodie',
  'Hm9qIuTogzY',
  'Malaysia-ல அப்படி Enna Panna ⁉️🔥🌚| #shorts',
  '148230',
  '14076',
  '28'),
 ('Peppa Foodie',
  'oMVl7RVH5pE',
  'Batu Caves Murugan Temple 🔥😍🇲🇾 | Peppa Foodie',
  '12375',
  '559',
  '7'),
 ('Peppa Foodie',
  'Fv3_6jXVAE8',
  'அப்பா Ku Surprise GIFT 🎁🎉 | #shorts',
  '500678',
  '35888',
  '157'),
 ('Peppa Foodie',
  'pPJp664_HYk',
  'Legendary Malaysian 🇲🇾 Restaurant in Chennai 🔥✨🎉 | #shortsen',
  '221628',
  '22593',
  '48'),
 ('Peppa Foodie',
  'iydxzyyHkPI',
  'TRENDING ⚡️ Spot in Malaysia 🇲🇾🔥| #shorts',
  '126884',
  '12754',
  '23'),
 ('Peppa Foodie',
  '-MFJHJxAlzE',
  'LOK LOK In Malaysia 🤢🔥❌ | #shorts',
  '1123440',
  '79417',
  '124'),
 ('Peppa Foodie',
  'DIksTLGTjnI',
  'தமிழன் அன்பு in Malaysia 🇲🇾♥️🫂 | #shorts',
  '413176',
  '39859',
  '38'),
 ('Peppa Foodie',
  'SRcNmJAbWxw',
  'மரண Mutton Sapadu 🥩😍🔥| #shorts',
  '1737912',
  '140971',
  '235'),
 ('Peppa Foodie',
  '9YMWKe_IuwA',
  "Let's Try CHINESE 🇨🇳 Breakfast ✨‼️| #shorts",
  '1272029',
  '82894',
  '145'),
 ('Peppa Foodie',
  'xoirwBxYEps',
  'Night Life 😍 of Malaysia 🇲🇾🔞 | #shorts',
  '1515930',
  '122178',
  '155'),
 ('Peppa Foodie',
  'hQvO5nzErLA',
  'Mango 🥭 Sticky Rice ♥️ நம்ம ஊரு சோறு Ah 🔥‼️| #shorts',
  '297998',
  '27427',
  '64'),
 ('Peppa Foodie',
  'sdc5ZXQfFu4',
  'Malaysia-ல இப்படி Oru Food Street ah 🔥🇲🇾‼️| #shorts',
  '396254',
  '36874',
  '55'),
 ('Peppa Foodie',
  'Ggz7-8z9zCk',
  'Roti Canai and Teh Tarik 🔥🇲🇾 in Malaysia | Peppa Foodie',
  '33744',
  '896',
  '15')]

In [ ]:
mycursor.execute("DROP TABLE Video_detail")
mydb.commit()

In [ ]:
mycursor.execute("""
    CREATE TABLE video_detail (
        channel_name VARCHAR(100),
        video_id VARCHAR(80),
        title VARCHAR(255),
        views INT,
        likes INT,
        comments INT
    )
""")
mydb.commit()

In [ ]:
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="1997",
  auth_plugin='mysql_native_password',
  database='youtubedata'
)

mycursor = mydb.cursor()

In [ ]:
sql = """
    INSERT INTO video_detail (channel_name, video_id, title, views, likes, comments)
    VALUES (%s, %s, %s, %s, %s, %s)
"""
values=videos

try:
    mycursor.executemany(sql, values)
    mydb.commit()
    print(mycursor.rowcount, "records inserted.")
except mysql.connector.Error as error:
    print(f"Error inserting data into MySQL table: {error}")
finally:
    mycursor.close()
    mydb.close()

50 records inserted.

In [ ]:
def comment_details(video_id):
    getcomments=[]
    for video_ids in video_id:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_ids,
            maxResults=50
        )
        response3 = request.execute()
        
        for item in response3['items']:
            data = {
                "video_id":item['snippet']['topLevelComment']['snippet']['videoId'],
                "comment_id": item['snippet']['topLevelComment']['id'],
                "comment_text": item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "comment_author": item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
            }
            getcomments.append(data)
        return getcomments

In [ ]:
comments=comment_details(video_id)

In [ ]:
comments

[{'video_id': '2u8qlSBykYY',
  'comment_id': 'Ugzh2_TyGyvvboPnXNt4AaABAg',
  'comment_text': 'My favourite combo ❤ whenever I visit Chennai I do enjoy both the places',
  'comment_author': '@kishandin'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgzyjsJSnR9NnCOY6jJ4AaABAg',
  'comment_text': 'Shree mithai layum kedaikum',
  'comment_author': '@venki3deditor'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgwsoOSOVQXGp_ooheJ4AaABAg',
  'comment_text': 'Now Agarwal bawan is open in Santhi colony, Anna Nagar',
  'comment_author': '@rabbani4u'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'Ugyd5G5TFCgIDdSHkUd4AaABAg',
  'comment_text': 'Mixed with vadakkans love ah',
  'comment_author': '@greensand7366'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgzFpy05nVTJekH9GXx4AaABAg',
  'comment_text': 'Chennai LA romba rare kadalai mittai😂😂😂',
  'comment_author': '@vigneshnagaraj7137'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgzsdBlTOmaraGcgYdV4AaABAg',
  'comment_text': 'Badshah enum super ah irukum try paniparunga',
  'comment_author': '@subramanigomathi8470'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgzvcZPC3oIzK-l-o0d4AaABAg',
  'comment_text': 'Ghewar❤',
  'comment_author': '@emceeakshayiyer3426'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgzowNqhhALDXX6r61N4AaABAg',
  'comment_text': '999th like and 6th comment 🎉',
  'comment_author': '@LUCKY_GAMER664'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgyI5EiXP92llt4UgXF4AaABAg',
  'comment_text': 'ANNA ❤ Fan&#39;s ♥️ one like 😊pin 📌 me 😊',
  'comment_author': '@rctamil-tg2kw'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'Ugx_RNNx-bU7yaoG8Pp4AaABAg',
  'comment_text': 'your T-shirt👕 wow sukuna❤😮 where did you buy bro❤❤',
  'comment_author': '@rajendrianlakshmi124'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'Ugyruc5dpFqznxL3uoJ4AaABAg',
  'comment_text': 'Mass 💥',
  'comment_author': '@gamingguru7361'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgzEdHjavKeYdmuplnt4AaABAg',
  'comment_text': 'Super',
  'comment_author': '@sujatha.p8189'},
 {'video_id': '2u8qlSBykYY',
  'comment_id': 'UgwjcD1PxFucHiXlzbx4AaABAg',
  'comment_text': 'first comment. bro neenga chennaila sapthadhu laye best biryani sollungah',
  'comment_author': '@niting7176'}]

In [ ]:
comment_data = []

# Process each dictionary in the list
for comment in comments:
    # Create a tuple from dictionary values and append to video_data
    data = tuple(comment.values())
    comment_data.append(data)

In [ ]:
comment=comment_data

In [ ]:
comment

[('2u8qlSBykYY',
  'Ugzh2_TyGyvvboPnXNt4AaABAg',
  'My favourite combo ❤ whenever I visit Chennai I do enjoy both the places',
  '@kishandin'),
 ('2u8qlSBykYY',
  'UgzyjsJSnR9NnCOY6jJ4AaABAg',
  'Shree mithai layum kedaikum',
  '@venki3deditor'),
 ('2u8qlSBykYY',
  'UgwsoOSOVQXGp_ooheJ4AaABAg',
  'Now Agarwal bawan is open in Santhi colony, Anna Nagar',
  '@rabbani4u'),
 ('2u8qlSBykYY',
  'Ugyd5G5TFCgIDdSHkUd4AaABAg',
  'Mixed with vadakkans love ah',
  '@greensand7366'),
 ('2u8qlSBykYY',
  'UgzFpy05nVTJekH9GXx4AaABAg',
  'Chennai LA romba rare kadalai mittai😂😂😂',
  '@vigneshnagaraj7137'),
 ('2u8qlSBykYY',
  'UgzsdBlTOmaraGcgYdV4AaABAg',
  'Badshah enum super ah irukum try paniparunga',
  '@subramanigomathi8470'),
 ('2u8qlSBykYY',
  'UgzvcZPC3oIzK-l-o0d4AaABAg',
  'Ghewar❤',
  '@emceeakshayiyer3426'),
 ('2u8qlSBykYY',
  'UgzowNqhhALDXX6r61N4AaABAg',
  '999th like and 6th comment 🎉',
  '@LUCKY_GAMER664'),
 ('2u8qlSBykYY',
  'UgyI5EiXP92llt4UgXF4AaABAg',
  'ANNA ❤ Fan&#39;s ♥️ one like 😊pin 📌 me 😊',
  '@rctamil-tg2kw'),
 ('2u8qlSBykYY',
  'Ugx_RNNx-bU7yaoG8Pp4AaABAg',
  'your T-shirt👕 wow sukuna❤😮 where did you buy bro❤❤',
  '@rajendrianlakshmi124'),
 ('2u8qlSBykYY', 'Ugyruc5dpFqznxL3uoJ4AaABAg', 'Mass 💥', '@gamingguru7361'),
 ('2u8qlSBykYY', 'UgzEdHjavKeYdmuplnt4AaABAg', 'Super', '@sujatha.p8189'),
 ('2u8qlSBykYY',
  'UgwjcD1PxFucHiXlzbx4AaABAg',
  'first comment. bro neenga chennaila sapthadhu laye best biryani sollungah',
  '@niting7176')]

In [ ]:
mycursor.execute("""
    CREATE TABLE comment_detail (
        video_id varchar(80),
        comment_id varchar(80),
        comments Text,
        comment_author varchar(30)
         )
""")
mydb.commit()

In [ ]:
sql = """
    INSERT INTO comment_detail (video_id,comment_id,comments,comment_author)
    VALUES (%s,%s,%s,%s)
"""

values =comment

try:
    mycursor.executemany(sql, values)
    mydb.commit()
    print(mycursor.rowcount, "records inserted.")


except mysql.connector.Error as error:
    print(f"Error inserting data into MySQL table: {error}")

finally:
    mycursor.close()
    mydb.close()

13 records inserted.

In [1]:
import streamlit as st

In [2]:
with st.sidebar:
    st.title(":red[Youtube Data Harvesting]")
    st.header("Take Away codes")
    st.caption("python scripting")
    st.caption("Data collection")
    st.caption("API integration")
    st.caption("Data management using Mysql")
    
channel_id=st.text_input("Enter the channel_id")
    

st.button("Migrate to MYSQL")
show_tables=st.radio("select table for view",("channels","Videos","comments"))

2024-06-22 06:43:53.766
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2024-06-22 06:43:53.766 Session state does not function when running a script without `streamlit run`